name: Run end-to-end tests using cypress

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npm start
          wait-on: "http://localhost:3000"
